default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rubitify_development
test:
  <<: *default
  database: rubitify_test
production:
  <<: *default
  database: rubitify_production
  username: <%= ENV['RUBYTIFY_DATABASE_USERNAME'] %>
  password: <%= ENV['RUBYTIFY_DATABASE_PASSWORD'] %>
